### ISSUE TITLE
Error : README third party extensions must be alphabetically sorted

### ISSUE THREAD

**Issue by zrfisaac** [simple-icons/simple-icons#7286]
### Kind of Issue

Bug

### This issue concerns the...

NPM package

### Package Version

6.16.0

### Other Software

None

### Description

When I run the following command a error appears
```
npm run test
```

Here is the output
```
> simple-icons@6.15.0 pretest
> npm run prepublishOnly


> simple-icons@6.15.0 prepublishOnly
> npm run build


> simple-icons@6.15.0 build
> node scripts/build/package.js


> simple-icons@6.15.0 test
> mocha tests --reporter tests/min-reporter.cjs --inline-diffs


  42075 passing (2s)
  1 failing

  1) README third party extensions must be alphabetically sorted:
     TypeError: Cannot read properties of undefined (reading 'split')
      at getThirdPartyExtensions (file:///D:/zrfisaac/work/zrfisaac/source/fork-simple-icons/scripts/utils.js:130:5)
      at async Context.<anonymous> (file:///D:/zrfisaac/work/zrfisaac/source/fork-simple-icons/tests/readme.test.js:51:32)
```

Does anybody know how to fix it ?

**Comment by zrfisaac** [comment]
My Node version is v16.14.2

**Comment by zrfisaac** [comment]
No, I Just run "npm run test" and show this error. Tomorrow I Will try find the problem. If I find the solution I Will post here.

**Comment by mondeja** [comment]
Could be a bug in Windows caused by the newline characters.
